"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Role = "manager" | "employee" | "auditor";
type Data = { versions: { id:string; weekStart:string; version:number; status:string }[]; shifts:{id:string;scheduleVersionId:string;userId:string;startsAt:string;endsAt:string;kind:string;status:string}[]; members:{id:string;name:string}[]; leaves:{id:string;requesterUserId:string;startDate:string;endDate:string;status:string}[]; teamProfile:"small"|"medium"|"large"; capabilities:{manage:boolean;publish:boolean} };
const empty:Data={versions:[],shifts:[],members:[],leaves:[],teamProfile:"small",capabilities:{manage:false,publish:false}};

export default function ScheduleWorkspace({role,notify}:{role:Role;notify:(x:string)=>void}){
 const [data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [view,setView]=useState<"today"|"week"|"oncall"|"leave">("today");
 const [selectedDate,setSelectedDate]=useState(()=>new Date().toISOString().slice(0,10));
 const load=useCallback(async()=>{const r=await fetch("/api/schedule",{cache:"no-store"});if(r.ok)setData(await r.json());else setError("Schedule data could not be loaded.");setLoading(false)},[]);
 useEffect(()=>{let live=true;fetch("/api/schedule",{cache:"no-store"}).then(async r=>{if(!live)return;if(r.ok)setData(await r.json());else setError("Schedule data could not be loaded.");setLoading(false)}).catch(()=>{if(live){setError("Schedule data could not be loaded.");setLoading(false)}});return()=>{live=false}},[]);
 async function act(url:string,method:string,payload:Record<string,unknown>,message:string){setError("");const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json().catch(()=>({}));if(!r.ok){setError(b.error??"The action could not be completed.");return false}notify(message);await load();return true}
 const active=data.versions.find(v=>v.status==="draft")??data.versions.find(v=>v.status==="published");
 const visibleShifts=active?data.shifts.filter(s=>s.scheduleVersionId===active.id):[];
 const conflicts=data.leaves.filter(l=>l.status==="approved"&&visibleShifts.some(s=>s.userId===l.requesterUserId&&day(s.startsAt)>=l.startDate&&day(s.startsAt)<=l.endDate));
 if(loading)return <div className="team-loading"><i/><p><strong>Loading workforce schedule</strong><span>Checking shifts, leave and conflicts…</span></p></div>;
 const dailyShifts=visibleShifts.filter(s=>day(s.startsAt)===selectedDate);
 const onCallShifts=visibleShifts.filter(s=>s.kind==="on_call");
 return <div className="schedule-workspace"><section className="schedule-title"><div><small>WORKFORCE OPERATIONS</small><h2>{view==="today"?"Daily ROTA":view==="week"?"Weekly schedule":view==="oncall"?"On-call coverage":"Leave requests"}</h2><p>See who is working, where coverage is missing, and what needs approval.</p></div><div className={`schedule-status ${active?.status??"empty"}`}><i/>{active?`${active.status} · v${active.version}`:"No schedule yet"}</div></section>
 {error&&<div className="setup-error">! {error}</div>}
 <nav className="rota-tabs" aria-label="Schedule views"><button className={view==="today"?"active":""} onClick={()=>setView("today")}>Today</button><button className={view==="week"?"active":""} onClick={()=>setView("week")}>Week</button>{data.teamProfile!=="small"&&<button className={view==="oncall"?"active":""} onClick={()=>setView("oncall")}>On-call <b>{onCallShifts.length}</b></button>}<button className={view==="leave"?"active":""} onClick={()=>setView("leave")}>Leave requests <b>{data.leaves.filter(x=>x.status==="pending").length}</b></button></nav>
 <section className="schedule-kpis"><Kpi value={String(visibleShifts.length)} label="Planned shifts"/><Kpi value={String(data.members.length)} label="Team members"/><Kpi value={String(data.leaves.filter(x=>x.status==="pending").length)} label="Leave requests"/><Kpi value={String(conflicts.length)} label="Conflicts" warning={conflicts.length>0}/></section>
 <section className="schedule-layout"><article className="schedule-board"><header><div><strong>{active?weekLabel(active.weekStart):"Current planning week"}</strong><span>{data.teamProfile==="small"?"Simple weekly view":data.teamProfile==="medium"?"Team and on-call view":"Advanced workforce view"}</span></div>{data.capabilities.publish&&active?.status==="draft"&&<button onClick={()=>void act("/api/schedule","POST",{action:"publish",scheduleVersionId:active.id},"Schedule published.")}>Publish schedule</button>}</header>
  {view==="today"?<DailyRota data={data} shifts={dailyShifts} date={selectedDate} setDate={setSelectedDate}/>:view==="week"?<ShiftList data={data} shifts={visibleShifts}/>:view==="oncall"?<ShiftList data={data} shifts={onCallShifts}/>:<LeaveBoard data={data} act={act}/>}
  {!data.capabilities.manage&&active?.status==="published"&&role==="employee"&&<button className="ack-button" onClick={()=>void act("/api/schedule","POST",{action:"acknowledge",scheduleVersionId:active.id},"Schedule acknowledged.")}>✓ Acknowledge schedule</button>}
 </article><aside className="schedule-side">{data.capabilities.manage?<ShiftForm data={data} act={act}/>:<LeaveForm act={act}/>}<article className="leave-panel"><header><strong>Leave requests</strong><span>{data.leaves.length}</span></header>{data.leaves.slice(0,5).map(l=><div key={l.id}><p><strong>{memberName(data,l.requesterUserId)}</strong><span>{l.startDate} → {l.endDate}</span></p><b className={l.status}>{l.status}</b>{data.capabilities.manage&&l.status==="pending"&&<aside><button onClick={()=>void act("/api/leave-requests","PATCH",{id:l.id,decision:"approved"},"Leave approved.")}>✓</button><button onClick={()=>void act("/api/leave-requests","PATCH",{id:l.id,decision:"rejected"},"Leave rejected.")}>×</button></aside>}</div>)}</article></aside></section>
 {conflicts.length>0&&<div className="conflict-banner"><b>!</b><p><strong>{conflicts.length} schedule conflict{conflicts.length>1?"s":""} detected</strong><span>An approved absence overlaps a planned shift. Resolve before publishing the next version.</span></p></div>}
 </div>
}
function DailyRota({data,shifts,date,setDate}:{data:Data;shifts:Data["shifts"];date:string;setDate:(x:string)=>void}){const hours=Array.from({length:17},(_,i)=>i+6);const working=new Set(shifts.filter(s=>s.kind!=="training").map(s=>s.userId));const absent=new Set(data.leaves.filter(l=>l.status==="approved"&&l.startDate<=date&&l.endDate>=date).map(l=>l.requesterUserId));const coverage=hours.map(hour=>shifts.filter(s=>{const a=new Date(s.startsAt).getHours(),b=new Date(s.endsAt).getHours();return s.kind!=="training"&&a<=hour&&b>hour}).length);const gaps=coverage.filter(x=>x===0).length;return <div className="daily-rota"><header><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div><span><i className="working"/>Working {working.size}</span><span><i className="away"/>Away {absent.size}</span><span><i className="gap"/>Uncovered {gaps}h</span></div></header><div className="rota-hours"><b>Employee</b>{hours.map(h=><span key={h}>{String(h).padStart(2,"0")}</span>)}</div>{data.members.map(member=>{const shift=shifts.find(s=>s.userId===member.id);const isAway=absent.has(member.id);return <div className="rota-person" key={member.id}><p><strong>{member.name}</strong><span>{isAway?"Approved leave":shift?`${time(shift.startsAt)}–${time(shift.endsAt)}`:"Not scheduled"}</span></p><div>{hours.map(h=>{const active=shift&&new Date(shift.startsAt).getHours()<=h&&new Date(shift.endsAt).getHours()>h;return <i key={h} className={isAway?"away":active?shift?.kind:""}/>})}</div></div>})}<div className="coverage-row"><p><strong>Coverage</strong><span>People working by hour</span></p><div>{coverage.map((n,i)=><i key={i} className={n===0?"gap":n===1?"low":"good"}>{n}</i>)}</div></div>{!data.members.length&&<div className="schedule-empty"><b>◎</b><strong>No team members yet</strong><span>Add members in Team before building the daily ROTA.</span></div>}</div>}
function ShiftList({data,shifts}:{data:Data;shifts:Data["shifts"]}){return shifts.length?<div className="shift-list">{shifts.map(s=><div className="shift-row" key={s.id}><div className={`shift-kind ${s.kind}`}>{s.kind==="on_call"?"ON":s.kind==="training"?"TR":"SH"}</div><p><strong>{memberName(data,s.userId)}</strong><span>{format(s.startsAt)} → {format(s.endsAt)}</span></p><b>{s.kind.replace("_"," ")}</b><em>{s.status}</em></div>)}</div>:<div className="schedule-empty"><b>□</b><strong>No matching shifts</strong><span>Add a shift to the current Draft schedule.</span></div>}
function LeaveBoard({data,act}:{data:Data;act:(u:string,m:string,p:Record<string,unknown>,s:string)=>Promise<boolean>}){return <div className="leave-board">{data.leaves.map(l=><div key={l.id}><p><strong>{memberName(data,l.requesterUserId)}</strong><span>{l.startDate} → {l.endDate}</span></p><b className={l.status}>{l.status}</b>{data.capabilities.manage&&l.status==="pending"&&<aside><button onClick={()=>void act("/api/leave-requests","PATCH",{id:l.id,decision:"approved"},"Leave approved.")}>Approve</button><button onClick={()=>void act("/api/leave-requests","PATCH",{id:l.id,decision:"rejected"},"Leave rejected.")}>Reject</button></aside>}</div>)}{!data.leaves.length&&<div className="schedule-empty"><b>☼</b><strong>No leave requests</strong><span>New employee requests will appear here.</span></div>}</div>}
function ShiftForm({data,act}:{data:Data;act:(u:string,m:string,p:Record<string,unknown>,s:string)=>Promise<boolean>}){const monday=useMemo(()=>{const d=new Date();const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d.toISOString().slice(0,10)},[]);const [userId,setUser]=useState(""),[date,setDate]=useState(monday),[start,setStart]=useState("08:00"),[end,setEnd]=useState("16:00"),[kind,setKind]=useState("regular");async function submit(e:FormEvent){e.preventDefault();await act("/api/schedule","POST",{action:"createShift",userId:userId||data.members[0]?.id,startsAt:`${date}T${start}:00+02:00`,endsAt:`${date}T${end}:00+02:00`,kind,weekStart:monday},"Shift added to Draft schedule.")}return <article className="shift-form"><header><strong>Add shift</strong><span>Conflict checked</span></header><form onSubmit={submit}><label>Employee<select value={userId} onChange={e=>setUser(e.target.value)}>{data.members.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><div><label>Starts<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Ends<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>{data.teamProfile!=="small"&&<label>Type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="regular">Regular shift</option><option value="on_call">On-call</option><option value="training">Training</option></select></label>}<button disabled={!data.members.length}>＋ Add to draft</button></form></article>}
function LeaveForm({act}:{act:(u:string,m:string,p:Record<string,unknown>,s:string)=>Promise<boolean>}){const [start,setStart]=useState(""),[end,setEnd]=useState("");return <article className="shift-form"><header><strong>Request time off</strong><span>Manager approval</span></header><form onSubmit={async e=>{e.preventDefault();if(await act("/api/leave-requests","POST",{startDate:start,endDate:end},"Leave request submitted.")){setStart("");setEnd("")}}}><label>From<input required type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input required type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><button>Submit request</button></form></article>}
function Kpi({value,label,warning}:{value:string;label:string;warning?:boolean}){return <article className={warning?"warning":""}><strong>{value}</strong><span>{label}</span></article>}
function day(value:string){return new Date(value).toISOString().slice(0,10)}function time(v:string){return new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit"}).format(new Date(v))}function memberName(data:Data,id:string){return data.members.find(x=>x.id===id)?.name??"Team member"}function format(v:string){return new Intl.DateTimeFormat("en-GB",{weekday:"short",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}function weekLabel(v:string){return `Week of ${new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric"}).format(new Date(v+"T12:00:00Z"))}`}
